### ISSUE TITLE
Tracking issue platform support

### ISSUE THREAD

**Issue by dvc94ch** [flutter-rs/flutter-rs#100]
- [x] Linux
- [ ] MacOS
  - [ ] icu symbols missing in dylib was reported by (@ea2973929)
- [ ] Android
  - [ ] handling redrawing and orientation changes it tricky (https://github.com/rust-windowing/winit/pull/1328)
  - [ ] attaching the javavm to a thread crashes (required for jni to locate app.so)
- [ ] Windows
  - [ ] building engine for windows #98
- [ ] iOS
  - [ ] Creating bindings for `flutter-engine-sys` fails, possibly related to (https://github.com/rust-lang/rust-bindgen/issues/1211)

**Comment by clouds56** [comment]
It would crash on start on macOS (debug mode).
I run `cargo install cargo-flutter`, and `git clone https://github.com/flutter-rs/flutter-app-template` then `cargo flutter run`

```
engine 2994f7e1e682039464cb25e31a78b86a3c59b695/macosx_x64-host_debug_unopt.zip

Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (6 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

cargo 1.40.0 (bc8e4c8be 2019-11-22)
rustc 1.40.0 (73528e339 2019-12-16)
stable-x86_64-apple-darwin (default)
cargo-flutter 0.1.12
```

<details>

```
Thread 5 Crashed:: io.flutter.io
0   com.apple.AppKit              	0x00007fff2fd08360 -[NSOpenGLContext update] + 520
1   flutter-app-template          	0x000000010e2870fa _$LT$$LP$$RP$$u20$as$u20$objc..message..MessageArguments$GT$::invoke::h9dde68adc40cee57 + 58 (mod.rs:129)
2   flutter-app-template          	0x000000010e284fee objc::message::platform::send_unverified::haea3f96903b7d611 + 110 (mod.rs:27)
3   flutter-app-template          	0x000000010de37051 glutin::platform_impl::platform_impl::Context::make_current::h83898bc0992324cb + 449 (<::objc::macros::msg_send macros>:17)
4   flutter-app-template          	0x000000010de1acae glutin::context::Context$LT$T$GT$::make_current::h379f190ef8d569c6 + 62 (context.rs:47)
5   flutter-app-template          	0x000000010de0fc9f glutin::windowed::ContextWrapper$LT$T$C$W$GT$::make_current::h9ea71f5dc18f8b21 + 127 (windowed.rs:252)
6   flutter-app-template          	0x000000010de470d5 flutter_winit::context::Context::make_current::h6600b9c2ea6d9916 + 293 (context.rs:23)
7   flutter-app-template          	0x000000010de39744 _$LT$flutter_winit..handler..WinitFlutterEngineHandler$u20$as$u20$flutter_engine..FlutterEngineHandler$GT$::make_resource_current::hfe7455bc41d9fb50 + 84 (handler.rs:61)
8   flutter-app-template          	0x000000010e126602 flutter_engine::flutter_callbacks::make_resource_current::h0d02aa747b5dae1c + 370 (flutter_callbacks.rs:62)
9   libflutter_engine.dylib       	0x000000011287d5c2 InferOpenGLPlatformViewCreationCallback(FlutterRendererConfig const*, void*, flutter::PlatformViewEmbedder::PlatformDispatchTable, std::__1::unique_ptr<flutter::EmbedderExternalViewEmbedder, std::__1::default_delete<flutter::EmbedderExternalViewEmbedder> >)::$_75::operator()() const + 50
10  libflutter_engine.dylib       	0x000000011287d50b decltype(std::__1::forward<InferOpenGLPlatformViewCreationCallback(FlutterRendererConfig const*, void*, flutter::PlatformViewEmbedder::PlatformDispatchTable, std::__1::unique_ptr<flutter::EmbedderExternalViewEmbedder, std::__1::default_delete<flutter::EmbedderExternalViewEmbedder> >)::$_75&>(fp)()) std::__1::__invoke<InferOpenGLPlatformViewCreationCallback(FlutterRendererConfig const*, void*, flutter::PlatformViewEmbedder::PlatformDispatchTable, std::__1::unique_ptr<flutter::EmbedderExternalViewEmbedder, std::__1::default_delete<flutter::EmbedderExternalViewEmbedder> >)::$_75&>(InferOpenGLPlatformViewCreationCallback(FlutterRendererConfig const*, void*, flutter::PlatformViewEmbedder::PlatformDispatchTable, std::__1::unique_ptr<flutter::EmbedderExternalViewEmbedder, std::__1::default_delete<flutter::EmbedderExternalViewEmbedder> >)::$_75&) + 43
11  libflutter_engine.dylib       	0x000000011287d44b bool std::__1::__invoke_void_return_wrapper<bool>::__call<InferOpenGLPlatformViewCreationCallback(FlutterRendererConfig const*, void*, flutter::PlatformViewEmbedder::PlatformDispatchTable, std::__1::unique_ptr<flutter::EmbedderExternalViewEmbedder, std::__1::default_delete<flutter::EmbedderExternalViewEmbedder> >)::$_75&>(InferOpenGLPlatformViewCreationCallback(FlutterRendererConfig const*, void*, flutter::PlatformViewEmbedder::PlatformDispatchTable, std::__1::unique_ptr<flutter::EmbedderExternalViewEmbedder, std::__1::default_delete<flutter::EmbedderExternalViewEmbedder> >)::$_75&) + 43
12  libflutter_engine.dylib       	0x000000011287b092 std::__1::__function::__func<InferOpenGLPlatformViewCreationCallback(FlutterRendererConfig const*, void*, flutter::PlatformViewEmbedder::PlatformDispatchTable, std::__1::unique_ptr<flutter::EmbedderExternalViewEmbedder, std::__1::default_delete<flutter::EmbedderExternalViewEmbedder> >)::$_75, std::__1::allocator<InferOpenGLPlatformViewCreationCallback(FlutterRendererConfig const*, void*, flutter::PlatformViewEmbedder::PlatformDispatchTable, std::__1::unique_ptr<flutter::EmbedderExternalViewEmbedder, std::__1::default_delete<flutter::EmbedderExternalViewEmbedder> >)::$_75>, bool ()>::operator()() + 50
13  libflutter_engine.dylib       	0x00000001129152e3 std::__1::function<bool ()>::operator()() const + 67
14  libflutter_engine.dylib       	0x0000000112915cc8 flutter::EmbedderSurfaceGL::CreateResourceContext() const + 120
15  libflutter_engine.dylib       	0x000000011293039f flutter::PlatformViewEmbedder::CreateResourceContext() const + 319
16  libflutter_engine.dylib       	0x0000000113cfe0fd flutter::Shell::CreateShellOnPlatformThread(flutter::DartVMRef, flutter::TaskRunners, flutter::WindowData, flutter::Settings, fml::RefPtr<flutter::DartSnapshot const>, std::__1::function<std::__1::unique_ptr<flutter::PlatformView, std::__1::default_delete<flutter::PlatformView> > (flutter::Shell&)> const&, std::__1::function<std::__1::unique_ptr<flutter::Rasterizer, std::__1::default_delete<flutter::Rasterizer> > (flutter::Shell&)> const&)::$_11::operator()() const + 109
17  libflutter_engine.dylib       	0x0000000113cfe01b decltype(std::__1::forward<flutter::Shell::CreateShellOnPlatformThread(flutter::DartVMRef, flutter::TaskRunners, flutter::WindowData, flutter::Settings, fml::RefPtr<flutter::DartSnapshot const>, std::__1::function<std::__1::unique_ptr<flutter::PlatformView, std::__1::default_delete<flutter::PlatformView> > (flutter::Shell&)> const&, std::__1::function<std::__1::unique_ptr<flutter::Rasterizer, std::__1::default_delete<flutter::Rasterizer> > (flutter::Shell&)> const&)::$_11&>(fp)()) std::__1::__invoke<flutter::Shell::CreateShellOnPlatformThread(flutter::DartVMRef, flutter::TaskRunners, flutter::WindowData, flutter::Settings, fml::RefPtr<flutter::DartSnapshot const>, std::__1::function<std::__1::unique_ptr<flutter::PlatformView, std::__1::default_delete<flutter::PlatformView> > (flutter::Shell&)> const&, std::__1::function<std::__1::unique_ptr<flutter::Rasterizer, std::__1::default_delete<flutter::Rasterizer> > (flutter::Shell&)> const&)::$_11&>(flutter::Shell::CreateShellOnPlatformThread(flutter::DartVMRef, flutter::TaskRunners, flutter::WindowData, flutter::Settings, fml::RefPtr<flutter::DartSnapshot const>, std::__1::function<std::__1::unique_ptr<flutter::PlatformView, std::__1::default_delete<flutter::PlatformView> > (flutter::Shell&)> const&, std::__1::function<std::__1::unique_ptr<flutter::Rasterizer, std::__1::default_delete<flutter::Rasterizer> > (flutter::Shell&)> const&)::$_11&) + 43
18  libflutter_engine.dylib       	0x0000000113cfdf6b void std::__1::__invoke_void_return_wrapper<void>::__call<flutter::Shell::CreateShellOnPlatformThread(flutter::DartVMRef, flutter::TaskRunners, flutter::WindowData, flutter::Settings, fml::RefPtr<flutter::DartSnapshot const>, std::__1::function<std::__1::unique_ptr<flutter::PlatformView, std::__1::default_delete<flutter::PlatformView> > (flutter::Shell&)> const&, std::__1::function<std::__1::unique_ptr<flutter::Rasterizer, std::__1::default_delete<flutter::Rasterizer> > (flutter::Shell&)> const&)::$_11&>(flutter::Shell::CreateShellOnPlatformThread(flutter::DartVMRef, flutter::TaskRunners, flutter::WindowData, flutter::Settings, fml::RefPtr<flutter::DartSnapshot const>, std::__1::function<std::__1::unique_ptr<flutter::PlatformView, std::__1::default_delete<flutter::PlatformView> > (flutter::Shell&)> const&, std::__1::function<std::__1::unique_ptr<flutter::Rasterizer, std::__1::default_delete<flutter::Rasterizer> > (flutter::Shell&)> const&)::$_11&) + 43
19  libflutter_engine.dylib       	0x0000000113cfbdd2 std::__1::__function::__func<flutter::Shell::CreateShellOnPlatformThread(flutter::DartVMRef, flutter::TaskRunners, flutter::WindowData, flutter::Settings, fml::RefPtr<flutter::DartSnapshot const>, std::__1::function<std::__1::unique_ptr<flutter::PlatformView, std::__1::default_delete<flutter::PlatformView> > (flutter::Shell&)> const&, std::__1::function<std::__1::unique_ptr<flutter::Rasterizer, std::__1::default_delete<flutter::Rasterizer> > (flutter::Shell&)> const&)::$_11, std::__1::allocator<flutter::Shell::CreateShellOnPlatformThread(flutter::DartVMRef, flutter::TaskRunners, flutter::WindowData, flutter::Settings, fml::RefPtr<flutter::DartSnapshot const>, std::__1::function<std::__1::unique_ptr<flutter::PlatformView, std::__1::default_delete<flutter::PlatformView> > (flutter::Shell&)> const&, std::__1::function<std::__1::unique_ptr<flutter::Rasterizer, std::__1::default_delete<flutter::Rasterizer> > (flutter::Shell&)> const&)::$_11>, void ()>::operator()() + 50
20  libflutter_engine.dylib       	0x00000001128a6923 std::__1::function<void ()>::operator()() const + 67
21  libflutter_engine.dylib       	0x000000011297438d fml::MessageLoopImpl::FlushTasks(fml::FlushType) + 237
22  libflutter_engine.dylib       	0x0000000112974208 fml::MessageLoopImpl::RunExpiredTasksNow() + 40
23  libflutter_engine.dylib       	0x000000011299d453 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 51
24  com.apple.CoreFoundation      	0x00007fff327b2804 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
25  com.apple.CoreFoundation      	0x00007fff327b23be __CFRunLoopDoTimer + 859
26  com.apple.CoreFoundation      	0x00007fff327b1e9e __CFRunLoopDoTimers + 317
27  com.apple.CoreFoundation      	0x00007fff32796aed __CFRunLoopRun + 2213
28  com.apple.CoreFoundation      	0x00007fff32795bd3 CFRunLoopRunSpecific + 499
29  libflutter_engine.dylib       	0x000000011299d8f0 fml::MessageLoopDarwin::Run() + 336
30  libflutter_engine.dylib       	0x00000001129740fd fml::MessageLoopImpl::DoRun() + 77
31  libflutter_engine.dylib       	0x0000000112972aeb fml::MessageLoop::Run() + 43
32  libflutter_engine.dylib       	0x0000000112995e0c fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0::operator()() const + 124
33  libflutter_engine.dylib       	0x0000000112995cbb decltype(std::__1::forward<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(fp)()) std::__1::__invoke<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0&&) + 43
34  libflutter_engine.dylib       	0x0000000112995bb3 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>&, std::__1::__tuple_indices<>) + 51
35  libflutter_engine.dylib       	0x0000000112995509 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) + 105
36  libsystem_pthread.dylib       	0x00007fff69ff6e65 _pthread_start + 148
37  libsystem_pthread.dylib       	0x00007fff69ff283b thread_start + 15
```
</details>

**Comment by dvc94ch** [comment]
@clouds56 some issues are fixed in the `texture-registry` branch (pointer handling was causing crashes on all platforms). Were you able to determine what is going on?

**Comment by clouds56** [comment]
Sorry, but I cannot find a branch called `texture-registry` in flutter-rs/flutter-rs.

**Comment by clouds56** [comment]
I've tried the branch and same fault occurs

```toml
flutter-engine = { git = "https://github.com/dvc94ch/flutter-rs", branch = "texture-registry" }
flutter-winit = { git = "https://github.com/dvc94ch/flutter-rs", branch = "texture-registry" }
```

**Comment by csnewman** [comment]
@clouds56 Would you mind experimenting with the latest master version (in github, not cargo.io)?

**Comment by clouds56** [comment]
@csnewman I've rebuilt the project using the latest master and with no luck (the same error).

**Comment by csnewman** [comment]
The error is within `glutin`, is this a winit bug or are we incorrectly calling glutin? (Seeing as it works on Linux, I'm assuming the former?)

**Comment by csnewman** [comment]
@clouds56 could you try editing the `WinitFlutterEngineHandlee` so the `make_resource_current` returns false, without doing anything?

**Comment by clouds56** [comment]
Could you explain a bit, which crate should I edit?

now code in flutter-app-template is
```rust
    let window = WindowBuilder::new().with_title("Flutter App Demo");
    let flutter = FlutterWindow::new(window, Path::new(&assets_dir).to_owned()).unwrap();
    let flutter = flutter.with_resource_context().unwrap();
```

**Comment by dvc94ch** [comment]
Updated the template to the latest flutter-rs. Commenting `let flutter = flutter.with_resource_context().unwrap();` should have the effect that @csnewman was trying to achieve.

**Comment by omar391** [comment]
How about adding tracking issue for supporting the Web? Probably via wasm and/or Yew @https://github.com/yewstack/yew
